import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

/** @type {import("eslint").Linter.Config[]} */
const eslintConfig = [
  // Ignore generated and static assets
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "public/sw.js",
      "public/workbox-*.js",
      "types/database.ts", // auto-generated by supabase gen types
    ],
  },
  // Inherit Next.js core web vitals rules (includes TypeScript + React)
  ...compat.extends("next/core-web-vitals"),
];

export default eslintConfig;
